import hashlib
import importlib.util
import json
from pathlib import Path

from .declare import PROTOCOL, declared_manifest
from .validation import validate_manifest

MANIFEST = 'manifest.json'
SOURCE = 'plugin.py'


class ArtifactError(Exception):
    """A package on disk does not match the manifest that describes it."""


def package_files(directory):
    """Every file the digest covers, keyed by POSIX-relative path.

    Sorted by that path string so the Go platform and the Python worker walk the
    package in exactly the same order. Generated bytecode and the manifest itself
    are excluded: the manifest carries the digest, and its contract is compared
    separately when the platform registers it.
    """
    directory = Path(directory)
    files = []
    for path in directory.rglob('*'):
        if not path.is_file():
            continue
        relative = path.relative_to(directory).as_posix()
        if relative == MANIFEST or path.suffix == '.pyc' or '__pycache__' in path.parts:
            continue
        files.append(relative)
    return sorted(files)


def digest(directory):
    """SHA-256 over the package's source files. Mirrored by plugin.Digest in Go."""
    directory = Path(directory)
    hasher = hashlib.sha256()
    for relative in package_files(directory):
        data = (directory / relative).read_bytes()
        hasher.update(relative.encode() + b'\0' + str(len(data)).encode() + b'\0' + data)
    return hasher.hexdigest()


def load_module(directory, module_name='workflow_installed_plugin'):
    """Import a package's plugin.py without adding it to sys.modules permanently."""
    source = Path(directory) / SOURCE
    specification = importlib.util.spec_from_file_location(module_name, source)
    if specification is None or specification.loader is None:
        raise ArtifactError(f'{directory}: {SOURCE} could not be loaded')
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


def declared(directory):
    """The manifest a package's code declares, without its digest."""
    module = load_module(directory)
    manifest = declared_manifest(module)
    if manifest is None:
        raise ArtifactError(
            f'{directory}: {SOURCE} declares no plugin. Decorate execute() with '
            '@action, @resource, or @trigger from workflow_sdk.'
        )
    return manifest


def build(directory):
    """Generate manifest.json from the package's declaration and seal it."""
    directory = Path(directory)
    manifest = declared(directory)
    validate_manifest(manifest, require_digest=False)
    manifest['digest'] = digest(directory)
    validate_manifest(manifest)
    (directory / MANIFEST).write_text(json.dumps(manifest, indent=2) + '\n')
    return manifest


def read(directory):
    """Read and structurally validate a package's manifest without hashing it."""
    directory = Path(directory)
    path = directory / MANIFEST
    if not path.exists():
        raise ArtifactError(
            f'{directory}: {MANIFEST} is missing. Run "workflow-plugin build" to generate it.'
        )
    manifest = json.loads(path.read_text())
    if manifest.get('protocol') != PROTOCOL:
        raise ArtifactError(f'{directory}: unsupported plugin protocol {manifest.get("protocol")!r}')
    validate_manifest(manifest)
    return manifest


def verify(directory, manifest=None):
    """Confirm the sealed digest still matches the files on disk."""
    directory = Path(directory)
    manifest = manifest if manifest is not None else read(directory)
    actual = digest(directory)
    if actual != manifest['digest']:
        raise ArtifactError(
            f'{manifest["name"]}@{manifest["version"]}: package contents do not match the sealed '
            f'digest (manifest {manifest["digest"][:12]}…, files {actual[:12]}…). '
            'Run "workflow-plugin build" after changing a plugin.'
        )
    return manifest


def catalog(root, *, verify_digests=False):
    """Every installed package, keyed by (name, version) -> (manifest, directory)."""
    result = {}
    for path in sorted(Path(root).glob('*/' + MANIFEST)):
        directory = path.parent.resolve()
        manifest = read(directory)
        if verify_digests:
            verify(directory, manifest)
        key = (manifest['name'], manifest['version'])
        if key in result:
            raise ArtifactError(f'{key[0]}@{key[1]} is installed twice')
        result[key] = (manifest, directory)
    return result


def resolve(root, name, version):
    """Look up one installed package and verify its digest before it is used."""
    installed = catalog(root)
    entry = installed.get((name, version))
    if entry is None:
        raise ArtifactError(f'{name}@{version} is not installed')
    manifest, directory = entry
    verify(directory, manifest)
    return manifest, directory


def drift(root):
    """Packages whose manifest no longer matches what their code declares."""
    stale = []
    for path in sorted(Path(root).glob('*/' + MANIFEST)):
        directory = path.parent.resolve()
        manifest = json.loads(path.read_text())
        expected = dict(declared(directory))
        expected['digest'] = digest(directory)
        if expected != manifest:
            stale.append(directory.name)
    return stale
