// Code generated by cmd/gentypes. DO NOT EDIT.
// Regenerate with: make types
//
// These mirror the Go wire contract in sdk/go/plugin and internal/platform.
// Schema is hand-written in ./schema because it describes the JSON Schema subset
// the inspector renders, which the Go side carries as an opaque map.

import type { Schema } from './schema';

export type { Schema };

/** The lifecycle a run moves through. Mirrors the runs.status check constraint. */
export type RunStatus =
  | 'queued'
  | 'running'
  | 'succeeded'
  | 'failed'
  | 'cancelled';

export type Port = {
  side?: 'left' | 'right' | 'top' | 'bottom';
  name: string;
  title: string;
  kind: 'data' | 'resource';
  resourceType?: string;
  required?: boolean;
  sensitive?: boolean;
  multiple?: boolean;
  schema: Schema;
};

export type Manifest = {
  protocol: string;
  name: string;
  version: string;
  title: string;
  description: string;
  category: string;
  kind: 'action' | 'resource' | 'trigger';
  configSchema: Schema;
  inputs: Port[];
  outputs: Port[];
  permissions: string[];
  metrics?: Metric[];
  logFields?: string[];
  digest: string;
};

export type Metric = {
  name: string;
  kind: string;
  unit: string;
  description: string;
};

export type WorkflowNode = {
  responsePort?: string;
  id: string;
  plugin: string;
  version: string;
  name: string;
  config: Record<string, unknown>;
  logFields?: string[];
  position: { x: number; y: number };
};

export type WorkflowEdge = {
  id: string;
  source: string;
  sourcePort: string;
  target: string;
  targetPort: string;
};

export type Graph = {
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
};

export type Workflow = {
  id: string;
  name: string;
  head: number;
  published: number | null;
  updatedAt: string;
  graph: Graph;
};

export type Revision = {
  revision: number;
  name: string;
  author: string;
  message: string;
  createdAt: string;
  graph: Graph;
};

export type Run = {
  id: string;
  workflowId: string;
  revision: number;
  status: RunStatus;
  attempt: number;
  error: string | null;
  createdAt: string;
  finishedAt: string | null;
};

export type RunDetail = {
  id: string;
  workflowId: string;
  revision: number;
  status: RunStatus;
  attempt: number;
  error: string | null;
  createdAt: string;
  finishedAt: string | null;
  input: unknown;
  output: unknown;
};

export type Step = {
  nodeId: string;
  attempt: number;
  status: RunStatus;
  error: string | null;
  startedAt: string;
  finishedAt: string | null;
};

export type Binding = {
  id: string;
  nodeId: string;
  mode: 'draft' | 'published';
  path: string;
  token: string;
  runId: string | null;
  receivedAt: string | null;
};

