// Command gentypes writes the browser's view of the wire contract from the Go
// structs that define it, so the two cannot drift.
//
//	go run ./cmd/gentypes
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/brian-nunez/app-builder/internal/platform"
	"github.com/brian-nunez/app-builder/sdk/go/plugin"
)

const output = "web/src/lib/types.ts"

// Every type the UI reads off the API, in the order it should appear.
var exported = []struct {
	Name string
	Type reflect.Type
}{
	{"Port", reflect.TypeOf(plugin.Port{})},
	{"Manifest", reflect.TypeOf(plugin.Manifest{})},
	{"Metric", reflect.TypeOf(plugin.Metric{})},
	{"WorkflowNode", reflect.TypeOf(plugin.Node{})},
	{"WorkflowEdge", reflect.TypeOf(plugin.Edge{})},
	{"Graph", reflect.TypeOf(plugin.Graph{})},
	{"Workflow", reflect.TypeOf(platform.Workflow{})},
	{"Revision", reflect.TypeOf(platform.Revision{})},
	{"Run", reflect.TypeOf(platform.Run{})},
	{"RunDetail", reflect.TypeOf(platform.RunDetail{})},
	{"Step", reflect.TypeOf(platform.Step{})},
	{"Binding", reflect.TypeOf(platform.Binding{})},
}

// Go type names that map to a TypeScript type declared by hand.
var named = map[string]string{
	"plugin.Schema": "Schema",
	"plugin.Node":   "WorkflowNode",
	"plugin.Edge":   "WorkflowEdge",
	"plugin.Graph":  "Graph",
	"plugin.Port":   "Port",
	"plugin.Metric": "Metric",
	"platform.Run":  "Run",
}

// Fields whose Go type is too loose to describe the values the UI relies on.
var refined = map[string]string{
	"Port.kind":        "'data' | 'resource'",
	"Port.side":        "'left' | 'right' | 'top' | 'bottom'",
	"Manifest.kind":    "'action' | 'resource' | 'trigger'",
	"Run.status":       "RunStatus",
	"RunDetail.status": "RunStatus",
	"Step.status":      "RunStatus",
	"Binding.mode":     "'draft' | 'published'",
}

func main() {
	check := flag.Bool("check", false, "fail if the generated file is out of date instead of writing it")
	flag.Parse()

	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/gentypes. DO NOT EDIT.\n")
	out.WriteString("// Regenerate with: make types\n//\n")
	out.WriteString("// These mirror the Go wire contract in sdk/go/plugin and internal/platform.\n")
	out.WriteString("// Schema is hand-written in ./schema because it describes the JSON Schema subset\n")
	out.WriteString("// the inspector renders, which the Go side carries as an opaque map.\n\n")
	out.WriteString("import type { Schema } from './schema';\n\n")
	out.WriteString("export type { Schema };\n\n")
	out.WriteString("/** The lifecycle a run moves through. Mirrors the runs.status check constraint. */\n")
	out.WriteString("export type RunStatus =\n  | 'queued'\n  | 'running'\n  | 'succeeded'\n  | 'failed'\n  | 'cancelled';\n\n")

	for _, item := range exported {
		render(&out, item.Name, item.Type)
	}
	if *check {
		existing, err := os.ReadFile(output)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, out.Bytes()) {
			fmt.Fprintf(os.Stderr, "%s is out of date; run \"make types\"\n", output)
			os.Exit(1)
		}
		fmt.Printf("%s is up to date\n", output)
		return
	}
	if err := os.WriteFile(output, out.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d types)\n", output, len(exported))
}

func render(out *bytes.Buffer, name string, t reflect.Type) {
	fmt.Fprintf(out, "export type %s = {\n", name)
	for _, field := range fields(t) {
		tag := field.Tag.Get("json")
		if tag == "-" {
			continue
		}
		parts := strings.Split(tag, ",")
		key := parts[0]
		if key == "" {
			key = strings.ToLower(field.Name[:1]) + field.Name[1:]
		}
		optional := ""
		nullable := false
		for _, option := range parts[1:] {
			if option == "omitempty" {
				optional = "?"
			}
		}
		fieldType := field.Type
		if fieldType.Kind() == reflect.Pointer {
			fieldType = fieldType.Elem()
			nullable = true
		}
		rendered := refined[name+"."+key]
		if rendered == "" {
			rendered = tsType(fieldType)
		}
		if nullable {
			rendered += " | null"
		}
		fmt.Fprintf(out, "  %s%s: %s;\n", key, optional, rendered)
	}
	out.WriteString("};\n\n")
}

// fields flattens embedded structs the way encoding/json does.
func fields(t reflect.Type) []reflect.StructField {
	var result []reflect.StructField
	for i := range t.NumField() {
		field := t.Field(i)
		if field.Anonymous && field.Type.Kind() == reflect.Struct {
			result = append(result, fields(field.Type)...)
			continue
		}
		if field.IsExported() {
			result = append(result, field)
		}
	}
	return result
}

func tsType(t reflect.Type) string {
	if key := t.PkgPath(); key != "" && t.Name() != "" {
		short := key[strings.LastIndex(key, "/")+1:] + "." + t.Name()
		if mapped, ok := named[short]; ok {
			return mapped
		}
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		return tsType(t.Elem()) + "[]"
	case reflect.Map:
		return "Record<string, " + tsType(t.Elem()) + ">"
	case reflect.Interface:
		return "unknown"
	case reflect.Pointer:
		return tsType(t.Elem()) + " | null"
	case reflect.Struct:
		var keys []string
		for _, field := range fields(t) {
			tag := strings.Split(field.Tag.Get("json"), ",")[0]
			if tag == "" || tag == "-" {
				tag = strings.ToLower(field.Name[:1]) + field.Name[1:]
			}
			keys = append(keys, fmt.Sprintf("%s: %s", tag, tsType(field.Type)))
		}
		sort.Strings(keys)
		return "{ " + strings.Join(keys, "; ") + " }"
	}
	return "unknown"
}
